### PR TITLE
Bugfixes and improvements

### PR DESCRIPTION
**Pull request by str4d**
Sourced from https://github.com/aschampion/schemer/issues/18.

### CODE REVIEW

**Comment by str4d** [comment]
I opened this PR with the exact commits from the fork-of-`schemer`. I'm now going to rebase them on our `main` to fix merge conflicts, and adjust the commits as necessary to document them appropriately.

**Comment by str4d** [comment]
[Rebased on `main`](https://github.com/zcash/schemerz/compare/64497ce4b66af9414c6e9615d1f426d11f36f326..0d52a90b60b8c1fd176b54d9626c51223603e820) to handle merge conflicts due to our fork.

**Comment by str4d** [comment]
[Force-pushed](https://github.com/zcash/schemerz/compare/0d52a90b60b8c1fd176b54d9626c51223603e820..2724f433f84384830d56f6a9a399e732138aa01c) to add changelog entries for each commit that alters the public API.

**Review by daira — APPROVED** [review]
utACK

**Pull request merged**
